#define MAX_BUF_SIZE 		1024
#define MAX_FILENAME_LENGTH 128
#define	MAX_MODE_LENGTH		128
#define BLOCK_SIZE			512

// OPCODES
#define RRQ		1
#define DATA	3
#define	ERROR	5

// ERROR NUMBERS
#define FILE_NOT_FOUND				1
#define	ILLEGAL_TFTP_OPERATION		4

// OPCODES
#define RRQ		1
#define DATA	3
#define	ERROR	5

// ERROR NUMBERS
#define FILE_NOT_FOUND				1
#define	ILLEGAL_TFTP_OPERATION		4
