#define MAX_BUF_SIZE 		1024
#define MAX_DATA_SIZE		516
#define MAX_FILENAME_LENGTH 128
#define	MAX_MODE_LENGTH		128
#define MAX_ERROR_LENGTH	128
#define BLOCK_SIZE			512
#define MAX_DIR_LENGTH 		512
#define MAX_CMD_LENGTH		128

// OPCODES
#define RRQ		1
#define DATA	3
#define	ERROR	5

// ERROR NUMBERS
#define FILE_NOT_FOUND				1
#define	ILLEGAL_TFTP_OPERATION		4

// OPCODES
#define RRQ		1
#define DATA	3
#define	ERROR	5

// ERROR NUMBERS
#define FILE_NOT_FOUND				1
#define	ILLEGAL_TFTP_OPERATION		4

// MODES
#define BIN 0
#define TXT 1
